# Codigo para probar creación de archivos de estrategia optima (estrategia "MAX")

In [1]:
import datetime

from crea_estrategia_optima import estrategia_optima

afp='HABITAT'
fecha_ini = datetime.datetime.strptime('2012-01-01', '%Y-%m-%d').date()
fecha_end = datetime.datetime.strptime('2015-01-01', '%Y-%m-%d').date()
monto_inicial = 100

df = estrategia_optima(afp, fecha_ini, fecha_end, monto_inicial)
df

   Fecha inicio Fecha término Sugerencia
0    2011-12-31    2012-01-31     100% A
1    2012-01-31    2012-02-29     100% A
2    2012-02-29    2012-03-31     100% A
3    2012-03-31    2012-04-30     100% E
4    2012-04-30    2012-05-31     100% E
5    2012-05-31    2012-06-30     100% C
6    2012-06-30    2012-07-31     100% E
7    2012-07-31    2012-08-31     100% E
8    2012-08-31    2012-09-30     100% A
9    2012-09-30    2012-10-31     100% A
10   2012-10-31    2012-11-30     100% E
11   2012-11-30    2012-12-31     100% A
12   2012-12-31    2013-01-31     100% A
13   2013-01-31    2013-02-28     100% E
14   2013-02-28    2013-03-31     100% E
15   2013-03-31    2013-04-30     100% E
16   2013-04-30    2013-05-31     100% A
17   2013-05-31    2013-06-30     100% E
18   2013-06-30    2013-07-31     100% A
19   2013-07-31    2013-08-31     100% E
20   2013-08-31    2013-09-30     100% A
21   2013-09-30    2013-10-31     100% A
22   2013-10-31    2013-11-30     100% A
23   2013-11-30    2013-12-31     100% E
24   2013-12-31    2014-01-31     100% E
25   2014-01-31    2014-02-28     100% A
26   2014-02-28    2014-03-31     100% E
27   2014-03-31    2014-04-30     100% A
28   2014-04-30    2014-05-31     100% A
29   2014-05-31    2014-06-30     100% A
30   2014-06-30    2014-07-31     100% A
31   2014-07-31    2014-08-31     100% A
32   2014-08-31    2014-09-30     100% D
33   2014-09-30    2014-10-31     100% E
34   2014-10-31    2014-11-30     100% A
35   2014-11-30    2014-12-31     100% E
36   2014-12-31    2015-01-01     100% A

In [2]:
df['Fecha inicio']

0     2011-12-31
1     2012-01-31
2     2012-02-29
3     2012-03-31
4     2012-04-30
5     2012-05-31
6     2012-06-30
7     2012-07-31
8     2012-08-31
9     2012-09-30
10    2012-10-31
11    2012-11-30
12    2012-12-31
13    2013-01-31
14    2013-02-28
15    2013-03-31
16    2013-04-30
17    2013-05-31
18    2013-06-30
19    2013-07-31
20    2013-08-31
21    2013-09-30
22    2013-10-31
23    2013-11-30
24    2013-12-31
25    2014-01-31
26    2014-02-28
27    2014-03-31
28    2014-04-30
29    2014-05-31
30    2014-06-30
31    2014-07-31
32    2014-08-31
33    2014-09-30
34    2014-10-31
35    2014-11-30
36    2014-12-31
Name: Fecha inicio, dtype: object